name: CI

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x, 22.x, 24.x, lts/* ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test package
        run: pnpm test

      - name: Package
        run: pnpm pack

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node-version == 'lts/*'
        with:
          name: lingui-react-router
          path: lingui-react-router*.tgz
          retention-days: 7

  publish:
    runs-on: ubuntu-latest
    environment: publish
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v5

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lingui-react-router

      - name: Verify package
        run: |
          tar -tzf lingui-react-router*.tgz | grep -q "package.json" || (echo "Invalid package content" && exit 1)

      - name: Publish package
        run: npm publish lingui-react-router*.tgz
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
